tennissite/home/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy, reverse

import views

urlpatterns = patterns('',
	url(r'^$', views.homepage, name="homepage"),
	url(r'^(?P<pk>\d+)/$', views.HomeUser.as_view(), name="homeuser"),
	url(r'^info', views.NameView.as_view(), name="infopage"),
)

tennissite/players/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy, reverse

import views

urlpatterns = patterns('',
	url(r'^$', views.playerpage, name="playerpage"),
	url(r'^mens/$', views.mens, name="mens"),
	url(r'^womens/$', views.womens, name="womens"),
)

tennissite/tennissite/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin

"""tennissite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url="/home/"), name ="homeredir"),
    url(r'^home/', include('home.urls', namespace="home")),
    url(r'^players/', include('players.urls', namespace="players")),
]

tennissite/home/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    firstname = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    
    def __unicode__(self):
		return "{0} {1}".format(self.firstname, self.lastname)

tennissite/players/models.py
from django.db import models

# Create your models here.

class Player(models.Model):
    name = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    dob = models.CharField(max_length=200)
    age = models.IntegerField()
    desc = models.CharField(max_length=200)
    grandslams_won = models.IntegerField(default=0)
    
    def __unicode__(self):
    	return self.name
    
class GrandSlam(models.Model):
	AUSTRALIAN = 'Australian Open'
	FRENCH = 'French Open'
	WIMBLEDON = 'Wimbledon'
	US = 'US Open'
	YEAR_IN_SCHOOL_CHOICES = (
		(AUSTRALIAN, AUSTRALIAN),
		(FRENCH, FRENCH),
		(WIMBLEDON, WIMBLEDON),
    	(US, US),
	)
	grandslam = models.CharField(max_length=50,
                        		choices=YEAR_IN_SCHOOL_CHOICES,
                            	default=AUSTRALIAN)
	player = models.ForeignKey(Player)
	year = models.IntegerField()

    

tennissite/home/forms.py
from django import forms
import models


class NameForm(forms.Form):
	firstname = forms.CharField(max_length=200)
	lastname = forms.CharField(max_length=200)
	

tennissite/home/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.views.generic import View, FormView, DetailView, ListView, TemplateView

import os
import models
from forms import NameForm

# Create your views here.


def homepage(request):
	context = {}
	return render(request, 'base.html', context)

class HomeUser(DetailView):
	model = models.User
	context_object_name = "user"
	template_name = "base.html"

	def get_context_data(self, *args, **kwargs):
	    context = super(HomeUser, self).get_context_data(*args, **kwargs)
	    return context


class NameView(FormView):
	template_name = "home/info.html"
	form_class = NameForm
	
	def form_valid(self, form):
		data = form.cleaned_data
		firstname = data['firstname']
		lastname = data['lastname']
		new = models.User(firstname=firstname, lastname=lastname)
		new.save()
		return HttpResponseRedirect(reverse("home:homeuser", kwargs={"pk":new.pk}))

tennissite/players/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.views.generic import View, FormView, DetailView, ListView, TemplateView

import os
import models

# Create your views here.

def playerpage(request):
	context = {}
	return render(request, 'players/playerpage.html', context)
	
def mens(request):
	context = {}
	return render(request, 'players/mens.html', context)
	
def womens(request):
	context = {}
	return render(request, 'players/womens.html', context)


	
"""
class PlayerDetail(DetailView):

    model = models.player
    context_object_name =  "player"
    template_name = "players.html"

    def get_context_data(self, *args, **kwargs):
        context = super(PlayerDetail, self).get_context_data(*args, **kwargs)
        return context
"""

tennissite/players/templates/players/mens.html
{% extends "base.html" %}

{% block title %} Players {% endblock title %}

{% block extra_js %}
{% endblock extra_js %}

{% block content %}

<h1 class="row text-center"> Men <h1>


<br />




{% endblock %}

tennissite/players/templates/players/playerpage.html
{% extends "base.html" %}

{% block title %} Players {% endblock title %}

{% block extra_js %}
{% endblock extra_js %}

{% block content %}

<h1 class="row text-center"> Featured <h1>


<br />




{% endblock %}

tennissite/players/templates/players/womens.html
{% extends "base.html" %}

{% block title %} Players {% endblock title %}

{% block extra_js %}
{% endblock extra_js %}

{% block content %}

<h1 class="row text-center"> Women <h1>


<br />




{% endblock %}

tennissite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

	<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<meta name="keywords" content="KLTennis, Tennis, Federer, Nadal, Djokovic">
        <meta name="description" content="">
        <meta name="author" content="Kamil Ladhani">
   		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title>Tennis - {% block title %}Home{% endblock title %}</title>

   		 <!-- Bootstrap -->
		 <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
		 <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
		 <link href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
		 
		 <!-- Added since dropdown wasn't working -->
		 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		 <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
		 <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
		 
   		 <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
   		 <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
   		 <!--[if lt IE 9]>
   	   	 <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
         <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
         <![endif]-->
    	
    <!-- CSS to enable hover dropdown in navbar -->
 		 <style> 
 		 .dropdown:hover .dropdown-menu {
			display: block;
		 }
		 </style>
		 
         {% block extra_head %}
         {% endblock extra_head %}
        
 	 </head>
  
  	<body>
		    <div class="navbar navbar-inverse" style="margin: 0px">
            <div class="container-fluid">
            	  <ul class="nav navbar-nav">
                  {% block home_active %}
            	    <a class="navbar-brand" href="{% url 'home:homepage' %}">KLTennis</a>
                  {% endblock home_active %}
                	{% block players_active %} 
                	<li class="dropdown">
            				<a href="{% url 'players:playerpage' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Players <span class="caret"></span>
                    </a>
          					<ul class="dropdown-menu">
            					<li><a href="{% url 'players:playerpage' %}">Featured</a></li>
           						<li><a href="{% url 'players:mens' %}">Men</a></li>
           						<li><a href="{% url 'players:womens' %}">Women</a></li>
          					</ul>
        			    </li>
        			    {% endblock players_active %} 
                </ul>
            </div>
        </div>

        
   	 	  {% block content %}

        <div style="background-color: #222222">
          <br />
          <br />
          <h1 class="row text-center" style="color:white;">
            Welcome to KLTennis!
          </h1>
          <p class="row text-center" style="color:white; font-size:22px; padding:20px"> 
            The latest tennis news and tactics at your fingertips. 
          </p>
          <br />
        </div>

        <br />

        <div> 
          <p class="row text-center" style="font-size:16px; padding:20px"> 
            Get up-to-date news on the biggest stars in the game, including: <br /> <br /> Roger Federer <br /> Rafael Nadal <br /> Novak Djokovic <br /> Andy Murray <br /> <br /> ...and many more!
          </p>
        </div>

        {% endblock content %}


    <footer>
  		<div class="row text-center">
              <div class="hidden-print legal col-sm-8 col-sm-offset-2" style="font-size:15px">
                 <hr style="border-color: black"/>
              	 Copyright &copy; 2017 Kamil Ladhani. All Rights Reserved.
              </div>
          </div>
      </footer>

        {% block foot_js %}
        <script src="js/jquery-1.11.0.min.js"></script>
        <script src="js/underscore-1.6.0.min.js"></script>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    	<!-- Include all compiled plugins (below), or include individual files as needed -->
    	<script src="js/bootstrap.min.js"></script>
        {% endblock foot_js %}

        {% block extra_js %}{% endblock extra_js %}

  	</body>
</html>